"""empty message

Revision ID: 924900a4cda2
Revises: 96c815c48926
Create Date: 2021-10-09 12:08:23.064432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '924900a4cda2'
down_revision = '96c815c48926'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firstname', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('lastname', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lastname')
    op.drop_column('users', 'firstname')
    # ### end Alembic commands ###
