"""empty message

Revision ID: 7532e6017bca
Revises: 924900a4cda2
Create Date: 2021-10-11 11:19:39.884554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7532e6017bca'
down_revision = '924900a4cda2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('createdAt', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('updatedAt', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updatedAt')
    op.drop_column('users', 'createdAt')
    op.drop_table('posts')
    # ### end Alembic commands ###
